### ISSUE TITLE
Can't open eiger image.

### ISSUE THREAD

**Issue by jbhopkins** [silx-kit/fabio#88]
Hey,

I'm not a regular (or anytime) fabio contributor, but I wanted to let you know an issue I've found, and this is the only place I've found to do it. I've been unable to use fabio to open eiger images. I've tried with fabio installed from pip and with fabio built from the current git (clone of silx-kit/fabio, as of 10 minutes ago. It claims to be 0.5.0a0. Thee error message (the same with both versions of fabio) is below and one of the test images I used is attached. I was testing this in ipython when I got the error.

I'm using:
OS X 10.10.5
Python 2.7.11
pillow 3.2.0
numpy 1.10.4
lxml 3.6.0
h5py 2.6.0

Error message:
```
In [4]: fname = 'align2_013_97_data_000002.h5'

In [5]: test = fabio.open(fname)
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-5-fb702862104b> in <module>()
----> 1 test = fabio.open(fname)

/Users/jbh246/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/fabio/openimage.pyc in openimage(filename, frame)
    131         obj = _openimage(filename)
    132         logger.debug("Attempting to read frame %s from %s with reader %s" % (frame, filename, obj.classname))
--> 133         obj = obj.read(obj.filename, frame)
    134     return obj
    135 

/Users/jbh246/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/fabio/eigerimage.pyc in read(self, fname, frame)
    152         else:
    153             self.currentframe = 0
--> 154             self.data = self.dataset[0][self.currentframe, :, :]
    155             return self
    156 

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2687)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2645)()

/Users/jbh246/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/h5py/_hl/dataset.pyc in __getitem__(self, args)
    480         mspace = h5s.create_simple(mshape)
    481         fspace = selection.id
--> 482         self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
    483 
    484         # Patch up the output for NumPy

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2687)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2645)()

h5py/h5d.pyx in h5py.h5d.DatasetID.read (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/h5d.c:3231)()

h5py/_proxy.pyx in h5py._proxy.dset_rw (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_proxy.c:1860)()

h5py/_proxy.pyx in h5py._proxy.H5PY_H5Dread (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_proxy.c:1508)()

IOError: Can't read data (Can't open directory)
```

File:
[align2_013_97_data_000002.h5.zip](https://github.com/silx-kit/fabio/files/600194/align2_013_97_data_000002.h5.zip)

**Comment by kif** [comment]
I don't know if you have seen my email on the h5py mailing list but have a look at:

https://github.com/silx-kit/hdf5plugin

where you can find the HDF5 plugins needed for the eiger.

**Comment by jbhopkins** [comment]
I did just see that, thanks! I think the missing piece is that the hdf5plugin library is not listed as a requirement (or recommended package) for fabio (nor is h5py, I think), so I didn't have it installed. If you updated the documentation accordingly, that might well help avoid folks having similar issues in the future.

Thanks for the help, and for the great library!

**Comment by kif** [comment]
On Fri, 18 Nov 2016 12:55:19 -0800
jbhopkins <notifications@github.com> wrote:

> I did just see that, thanks! I think the missing piece is that the hdf5plugin library is not listed as a requirement (or recommended package) for fabio (nor is h5py, I think), so I didn't have it installed. If you updated the documentation accordingly, that might well help avoid folks having similar issues in the future.

Fabio is an open-source project, feel free to submit a pull-request for updating the documentation, or to send us an updated text.

> 
> Thanks for the help, and for the great library!

Can we close the issue ?

Cheers,

**Comment by jbhopkins** [comment]
I don't think the issue is actually fixed in fabio itself. If I import hdf5plugin before I import fabio, then I can open an eiger image. If I don't, then fabio throws the error I've listed above. I think that the import probably ought to happen in fabio itself, which ought to be an easy change to make. Then eiger images will always import correctly, assuming that the user has the hdf5plugin installed.

If you think that change isn't necessary, you're welcome to close the ticket. Personally, I'd suggesting adding that import statement at an appropriate place, or other folks might contact you with the same question when they try it later.

**Comment by vallsv** [comment]
I have no idea for the import while the list of hdf5plugin is not fixed, and i dont know if eiger output always use that encoding. But at least we should raise a better exception. But according to your back trace, h5py looks to be not very helpful. Any idea jerome?

**Comment by kif** [comment]
Dear Jesse, 

You have to understand those plugins are to be plugged into the HDF5 library;  which is available under Python via h5py, that FabIO wraps to expose the file as others. Hence FabIO is very far away from those plugins which makes your request not easy.

On the other hand, the silx-team is willing to provide the (synchrotron-) users with software to analyse their data. Compiling those plugins is rather tricky under windows (and also a bit under macOS) this is why we made this *hdf5plugin* but understand this is a HACK and should by no way be generalized.

Dectris has paid the HDFgroup for having those plugins. Since the Eiger was launched, 2 years ago, they are already at their second plugin (lz4 then bitshuffle-lz4). Those plugins are a changing target.

The "clean" way of doing things would be to ask hdf5  via h5py for the list of plugins available and if the LZ4 / LZ4-bitshuffle is missing to try to import the *hdf5plugin*.

@andrewcollette, is there a way to probe for the list of plugins ?
I put Andrew Collette in copy as it is directly linked to h5py. 
Maybe we should open an issue on h5py and discuss there.

Cheers,
Jerome

**Comment by vallsv** [comment]
BYI, here is a way to check of filters of a dataset https://github.com/silx-kit/silx/issues/571

**Comment by kif** [comment]
We have now a new set of hdf5plugins which works with a much broader spectrum ... but I am still reluctant to make them a requirement for fabio.
